### ISSUE TITLE
Is there a way to "sort" the users' friends by a field on the profile

### ISSUE THREAD

**Issue by jerocosio** [copleykj/socialize-friendships#20]
Hi, I'm using this amazing package like this:

```
{{#each usuario.friends}}
        {{#ionItem class="item-checkbox checkbox-amigos"}}
          <label class="checkbox">
            <input type="checkbox" value="{{user._id}}" name="amigos"/>
          </label>
          {{user.profile.nombre}} {{user.profile.apellidos}} ({{user.emails.[0].address}})
        {{/ionItem}}
      {{/each}}
```

```
usuario: function(){
    return Meteor.user();
  },
```

but I would like to know if there is a way to sort the order on which this users get displayed, maybe by their first or last name, thanks in advance!

**Comment by copleykj** [comment]
So currently there isn't a way to do this.. but there is a friendsAsUsers function defined on the User model that could be used as a nice template to add another function to the User class.

``` javascript
User.methods({
    sortedFriendsAsUsers: function (limit, skip, sortBy, sortOrder) {
        var options = {};

        var ids = this.friends(limit, skip).map(function(friend){
            return friend.friendId;
        });

        if(sortBy && sortOrder){
            sort[sortBy] = sortOrder;
            options.sort = sort;
        }

        return Meteor.users.find({_id:{$in:ids}}, options);
    }
})
```

then it could be used in the place of the friends function like this.

``` html
{{#each usuario.sortedFriendsAsUsers null null "fieldName", -1}}
    {{#ionItem class="item-checkbox checkbox-amigos"}}
        <label class="checkbox">
            <input type="checkbox" value="{{_id}}" name="amigos"/>
        </label>
        {{profile.nombre}} {{profile.apellidos}} ({{emails.[0].address}})
    {{/ionItem}}
{{/each}}
```

Also I personally recommend not using the profile key on the user record and instead creating separate records in a profile collection.. The socialize:user-profile package was intended for this.. Then instead of returning a users collection cursor from your newly created method, you can return a profiles collection cursor and plug up the gaping security hole that the profile key leaves in your app.
