### ISSUE TITLE
Friend request to yourself

### ISSUE THREAD

**Issue by expandboard** [copleykj/socialize-friendships#25]
user.requestFriendship(); allow to User send a request to himself.
it is an idle request.

**Comment by StorytellerCZ** [comment]
That is something you would normally guard against in your app, but we might as well include a check for it in the package.

**Comment by expandboard** [comment]
anyway this project is great work. i m new comer in Socialize packages and i try to develop it.
this package needs better documents. that s a necessary package and you can feel the vacuum of the good social packages in Atmosphere library.

**Comment by copleykj** [comment]
This is actually guarded against already and  I think allowing it would be a weird experience for end users.

You can always add them as their own friend automatically. This has been useful for me in the past because it allows an easy way to include a users own posts in their feed just by querying for posts that are from their friends.
