### ISSUE TITLE
Requesting friendship after denying request

### ISSUE THREAD

**Issue by paulgration** [copleykj/socialize-friendships#3]
Not sure how you feel about this one but I was thinking about the following scenario:

User Alice requests Bob as a friend.
Bob denies the request.

My understanding at this point is that Alice can't make another request until after `restrictRequestDays` days has expired (30 by default).
However if Bob decides within the 30 days (maybe even the next day) that he **does** want to be friends with Alice, he can't make a request to her because there is a restriction in place in the RequestsCollection insert function which ensures there aren't any existing requests that are denied or within the `restrictRequestDays` period in either direction.
So my thinking is, that Bob should be able to request Alice as a friend, having already recently denied her..

I've done a quick test by removing the `requester.hasRequestFrom(user)` check in the insert and this seems to work, so the line now looks like this:

`var pendingRequests = user.hasRequestFrom(requester);`

What do you think? I'm wondering if there are scenarios where denying a user's friendship request should then not allow you to make a friend request back to them for a period but figured you would have thought of some when developing this bit..

I was also wondering, when a friend request is accepted, whether the requests should be removed in both directions from the RequestsCollection? Currently it looks like it's only one way:

`RequestsCollection.remove({userId:document.userId, requesterId:document.friendId});`

**Comment by copleykj** [comment]
So basically I had sort of a divergent thought here and hadn't come back around to it.. I thought that perhaps a user could choose to ignore a request and then come back to it later.. I thinking on it though it's probably sufficient to just have deny and not over complicate things more than they have to be. I'm thinking the logic will need to be changed up a bit because I don't think that a request should be able to be sent in both directions if is a pending request in one direction already.

As for removing the requests in both directions, in the current implementation, the one way removal is sufficient because the request can only be from one use to the other, but with the change discussed above, it would be good to do a two way removal since both could exist.

**Comment by paulgration** [comment]
It looks like the FB model is that you can either Confirm or Delete a friend request, or just leave it (ignoring) as you've suggested - looks like there is an option to hide them as well perhaps or maybe I've been reading old documentation. So this would seem to fit with your thinking.. I guess when a request is deleted by the requestee this allows the requester to send a new one, but at this point the requestee could chose to ignore or block, or could presumably initialise a request the other way? Not entirely sure.
Also, similarly to what you've said, they only allow a currently pending request in one direction.

**Comment by copleykj** [comment]
I've added an ignore method. I think this should fit your use case, if not let me know.
